<?php
declare(strict_types=1);
require_once __DIR__ . '/form-abuse.php';
header('X-Robots-Tag: noindex, nofollow'); header('Content-Type: application/json; charset=utf-8'); $origin = trim((string) ($_SERVER['HTTP_ORIGIN'] ?? '')); $referer = trim((string) ($_SERVER['HTTP_REFERER'] ?? '')); $same_site = $origin === '' && (bool) preg_match('#^https://(www\.)?steepstep\.com(?:/|$)#i', $referer); if (!in_array($origin, ['https://steepstep.com', 'https://www.steepstep.com'], true) && !$same_site) ss_json(403, 'Diese Anfrage ist nicht erlaubt.'); if ($origin !== '') header('Access-Control-Allow-Origin: ' . $origin);
if ($_SERVER['REQUEST_METHOD'] !== 'POST') ss_json(405, 'Methode nicht erlaubt.'); if ((int) ($_SERVER['CONTENT_LENGTH'] ?? 0) > 65536) ss_json(413, 'Die Anfrage ist zu gross.'); $secret = ss_secret(); if ($secret === '' || !ss_token_valid(trim((string) ($_POST['_token'] ?? '')), $secret, 'contact')) ss_json(400, 'Der Spam-Schutz ist abgelaufen. Bitte laden Sie die Seite neu.');
if (!empty($_POST['website'])) ss_json(200, 'Ihre Nachricht wurde gesendet.'); $started = (int) ($_POST['form_started'] ?? 0); $elapsed = (int) round(microtime(true) * 1000) - $started; if ($started <= 0 || $elapsed < 4000 || $elapsed > 14400000) ss_json(200, 'Ihre Nachricht wurde gesendet.');
$name = ss_header_safe(strip_tags((string) ($_POST['name'] ?? ''))); $email = trim((string) filter_var($_POST['email'] ?? '', FILTER_SANITIZE_EMAIL)); $message = trim(strip_tags((string) ($_POST['message'] ?? ''))); if ($name === '' || $message === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) ss_json(400, 'Bitte füllen Sie Name, E-Mail-Adresse und Nachricht korrekt aus.'); if (mb_strlen($message) < 30) ss_json(400, 'Bitte beschreiben Sie Ihr Anliegen etwas ausführlicher, mindestens 30 Zeichen.');
if (!ss_captcha_valid((string) ($_POST['captcha_challenge'] ?? ''), $_POST['captcha_answer'] ?? null, $secret)) ss_json(400, 'Die Antwort auf die Rechenaufgabe stimmt nicht.'); if (preg_match('#(https?://|www\\.)#i', $name) || preg_match_all('#(https?://|www\\.)#i', $message) > 3) ss_json(200, 'Ihre Nachricht wurde gesendet.'); if (!ss_rate('ip', trim((string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown')), 5, 86400, $secret) || !ss_rate('email', strtolower($email), 3, 86400, $secret)) { header('Retry-After: 86400'); ss_json(429, 'Zu viele Anfragen. Bitte versuchen Sie es morgen erneut.'); }
$subject = 'Neue Kontaktanfrage via steepstep.com'; $body = "Neue Kontaktanfrage via steepstep.com\n\nName: $name\nE-Mail: $email\n\nNachricht:\n$message\n"; $headers = "From: steepstep Kontakt <noreply@steepstep.com>\r\nReply-To: $name <$email>\r\nContent-Type: text/plain; charset=utf-8\r\nX-Mailer: PHP/" . phpversion(); if (!mail('contact@steepstep.com', $subject, $body, $headers)) ss_json(500, 'Die E-Mail konnte nicht gesendet werden. Bitte schreiben Sie uns direkt an contact@steepstep.com.'); ss_json(200, 'Ihre Nachricht wurde gesendet.');
